project:
  type: book

book:
  title: "My PhD Thesis"
  author: "Po-Kai Yang"
  chapters:
    - index.qmd
    - abstract-en.qmd
    - chapters/01-intro.qmd
    - chapters/02-methods.qmd
    - chapters/03-results.qmd
    - chapters/04-discussion.qmd
    - chapters/05-conclusion.qmd
    - chapters/06-future.qmd
    - chapters/references.qmd

execute:
  echo: false
  warning: false
  message: false

bibliography: ref/references.bib
csl: ref/csl/american-medical-association.csl
suppress-bibliography: false

format:
  html:
    toc: true
    number-sections: true
  pdf:
    documentclass: book
    classoption: [openany, oneside]
    pdf-engine: xelatex
    fontsize: 12pt
    geometry:
      - left=2.5cm
      - right=2.5cm
      - top=2.5cm
      - bottom=2.5cm
    fig-pos: "H"
    tbl-pos: "H"
    include-in-header:
      text: |
        \usepackage{float}
        \usepackage{placeins}
        \usepackage{fontspec}
        \usepackage{xeCJK}
        \usepackage{setspace}
        \usepackage{titlesec}
        \usepackage{placeins}
        \setmainfont{texgyreheros-regular.otf}[
          Path = fonts/,
          BoldFont = texgyreheros-bold.otf,
          ItalicFont = texgyreheros-italic.otf,
          BoldItalicFont = texgyreheros-bolditalic.otf
        ]
        \setCJKmainfont{NotoSansCJKtc-Regular.otf}[
          Path = fonts/,
          BoldFont = NotoSansCJKtc-Bold.otf
        ]
        \setstretch{1.5}
        \setlength{\parindent}{0pt}
        \setlength{\parskip}{6pt}
        \titleformat{\chapter}[block]
          {\centering\bfseries\fontsize{18}{27}\selectfont}
          {\chaptername\ \thechapter.}{0.5em}{}
        \titlespacing*{\chapter}{0pt}{-20pt}{24pt}
        \titleformat{\section}
          {\bfseries\fontsize{14}{21}\selectfont}
          {\thesection}{1em}{}
        \titlespacing*{\section}{0pt}{12pt}{6pt}
        \titleformat{\subsection}
          {\bfseries\fontsize{12}{18}\selectfont}
          {\thesubsection}{1em}{}
        \titlespacing*{\subsection}{0pt}{10pt}{4pt}
        \usepackage{caption}
        \raggedbottom
        \captionsetup[table]{font=bf}
        \captionsetup[figure]{labelfont=bf,textfont=normalfont}
        \usepackage{ragged2e}
        \usepackage{etoolbox}
        \newif\iffirstsection
        \firstsectiontrue
        \pretocmd{\chapter}{\firstsectiontrue}{}{}
        \pretocmd{\section}{\FloatBarrier\iffirstsection\firstsectionfalse\else\clearpage\fi}{}{}
        \pretocmd{\subsection}{\FloatBarrier}{}{}
        \AtBeginEnvironment{CSLReferences}{\RaggedRight}
        \renewcommand{\maketitle}{}
        \let\realmainmatter\mainmatter
        \renewcommand{\mainmatter}{}
    include-before-body:
      - cover.tex
    toc: false
    number-sections: true
  docx:
    toc: true
    number-sections: true
