project:
  type: book

book:
  title: "My PhD Thesis"
  author: "Po-Kai Yang"
  chapters:
    - index.qmd
    - chapters/01-intro.qmd
    - chapters/02-methods.qmd
    - chapters/03-results.qmd
    - chapters/04-discussion.qmd
    - chapters/05-conclusion.qmd
    - chapters/references.qmd

execute:
  echo: false
  warning: false
  message: false

bibliography: ref/references.bib
csl: ref/csl/american-medical-association.csl
suppress-bibliography: true

format:
  html:
    toc: true
    number-sections: true
  pdf:
    documentclass: book
    pdf-engine: xelatex
    fontsize: 12pt
    include-in-header:
      text: |
        \usepackage{fontspec}
        \usepackage{xeCJK}
        \usepackage{setspace}
        \usepackage{titlesec}
        \setmainfont{Calibri}
        \setCJKmainfont{Microsoft JhengHei}
        \setstretch{1.5}
        \titleformat{\chapter}[display]
          {\bfseries\fontsize{16}{24}\selectfont}
          {\chaptername\ \thechapter}{12pt}{}
        \titleformat{\section}
          {\bfseries\fontsize{14}{21}\selectfont}
          {\thesection}{1em}{}
    toc: true
    number-sections: true
  docx:
    toc: true
    number-sections: true
